export const IMG_DETAIL_REQUEST = "IMG_DETAIL_REQUEST";
export const IMG_DETAIL_SUCCESS = "IMG_DETAIL_SUCCESS";
export const IMG_DETAIL_FAIL = "IMG_DETAIL_FAIL";



export const IMAGE_ML_DETAIL_REQUEST = "IMAGE_ML_DETAIL_REQUEST"
export const IMAGE_ML_DETAIL_SUCCESS = "IMAGE_ML_DETAIL_SUCCESS"
export const IMAGE_ML_DETAIL_FAIL = "IMAGE_ML_DETAIL_FAIL"